version: "3"

services:
  api:
    image: node:10
    user: "node"
    environment:
      - PORT=8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8000:8000"
    expose:
      - "8000"
    volumes:
      - ./:/home/node/app
    working_dir: /home/node/app
    command: "npm start"
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/api/status"]
      interval: 10s
      timeout: 1s
      retries: 3

  db:
    image: postgres
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
